services:
  frontend:
    build: ./frontend/auth-demo
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend/auth-demo:/app
    container_name: frontend-container

  keycloak-demo:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-demo
    command: ['start-dev']
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://postgres-demo/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "127.0.0.1:4884:8080" #extern:intern
    depends_on:
      - postgres-demo

  postgres-demo:
    image: postgres:latest
    container_name: postgres-demo
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data